services:
  jclipper:
    container_name: jclipper
    env_file:
      - .env
    image: jermanoid/jclipper:latest
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - /path/to/movies:/movies:ro  #Movies directory
      - /path/to/tv_shows:/tv:ro    #TV shows directory (Show/Season/episode structure)
      - /path/to/output_clips:/output #Output directory
